### ISSUE TITLE
Update to reflect changes in derby 0.9.1 and sharedb 1.0.0-beta5

### ISSUE THREAD

**Issue by ChrisSG** [derbyparty/racer-highway#10]
Compatibility seems broken with the latest releases of derby and sharedb.

**Comment by nateps** [comment]
The change was that we decided it was cleaner to have the connection stream do the JSON.parse. Can fix this by doing JSON.parse on the message before calling stream.push.

**Comment by michael-brade** [comment]
Excellent, thanks @zag2art, that fixed my crashes :+1:
