### ISSUE TITLE
Poor api design

### ISSUE THREAD

**Issue by droganov** [derbyparty/racer-highway#5]
Browser component is designed to be used along with browserify, it just force you to have certain environment outside the component. As a result, you can't use the transport with webpack for example.

It think, that proper design would allow the component, to be used like:
require("racer-highway/lib/browser”)(racer, clientOptions);

I can fork the project and make adjustments, but it would require changes to be made with derby-starter.

**Comment by zag2art** [comment]
Feel free to fork it. But actually we use it with webpack - look here - https://github.com/dmapper/derby-webpack

**Comment by droganov** [comment]
Hm, how do handle this line in `browser.js`?
`var CLIENT_OPTIONS = JSON.parse('{{clientOptions}}');`

When I try to require `browser.js` with webpack I get an error. And as I know derby imports it like a string, then does placeholder replace options an then add it to the bundle.

That's what I really don't like.

Locally I did this:
```
var racer = require("racer");

module.exports = function( racer, CLIENT_OPTIONS ){
  var BCSocket = require("browserchannel/dist/bcsocket-uncompressed").BCSocket;

  racer.Model.prototype._createSocket = function(bundle) {
    return new Socket(CLIENT_OPTIONS);
  };
```

And use it this way without derby and browserify

```
"use strict"

racer 			= require "racer"
highway 		= require "./tmp/racer-highway/lib/browser"

module.exports =
	start: ( options, cb ) ->
		highway racer, options.highway
```

And here is the problem, if I make a pull request you'll have to update boilerplates, But if I don't, then I'll have to use a static copy of the module.

**Comment by zag2art** [comment]
I've accepted @woodcoder's PR #6 and refactor client part a little bit. Do you have additional suggestions?

**Comment by droganov** [comment]
Hello Arthur, I can only send thank you, to you and to @woodcoder. As for the library, I'm waiting them to release react/relay/react-router to production (currently relay throws and exception when you request it in the server). After that I'll update proton-starter.
